### ISSUE TITLE
TransferJob: Error 400: Project id was not specified.

### ISSUE THREAD

**Issue by akoenig** [pulumi/pulumi-google-native#107]
We're utilizing `storagetransfer.v1.TransferJob` for creating a transfer job which syncs files from an AWS S3 bucket to a GCS bucket. Everything works as expected when using a `pulumi up --refresh` initially. The job gets created as expected.

Unfortunately, when making changes, for example deploying CloudRun services we receive a `Error 409: Conflict for resource '...': version '1622794891561214' was specified but current version is '1622797318138247'` which is somehow another problem, but we solved this by using `pulumi up --refresh` as a workaround in the past. Nevertheless, now, when using the `TransferJob`, this command doesn't work anymore as it fails with the following error: `google-native:storagetransfer/v1:TransferJob: Error 400: Project id was not specified.`.

This is the `TransferJob` definition.

```ts
const transferJob = new gcpNative.storagetransfer.v1.TransferJob(
  transferJobName,
  {
    transferJobsId: transferJobName,
    description: `${name}-s3-to-gcs-sync`,
    status: "ENABLED",
    schedule: {
      repeatInterval: "3600s", // every hour
      scheduleStartDate: {
        day: 1,
        month: 5,
        year: 2021,
      },
    },
    projectId: project,
    transferSpec: {
      awsS3DataSource: {
        awsAccessKey: {
          accessKeyId: config.getSecret("aws-access-key-id"),
          secretAccessKey: config.getSecret("aws-secret-access-key"),
        },
        bucketName: "my-bucket",
      },
      gcsDataSink: {
        bucketName: transferJobBucketName,
      },
      objectConditions: {
        includePrefixes: ["my/path/i-want-to-sync/"],
      },
      transferOptions: {
        deleteObjectsFromSourceAfterTransfer: false,
      },
    },
  }
);
```

At the moment, we're in a kind of deadlock situation as our workaround doesn't work anymore as well. Therefore, any hint is highly appreciated 🙂 

## Steps to reproduce

1. Create a `TransferJob`
2. Perform a `pulumi up --refresh`. Everything works as expected.
3. Perform a `pulumi up --refresh` again.
4. See error.

Expected: No `Error 400: Project id was not specified.` error

Actual: `Error 400: Project id was not specified.`

**Comment by akoenig** [comment]
This might be useful: https://github.com/googleapis/google-api-go-client/issues/466

**Comment by mikhailshilkov** [comment]
Hi @akoenig sorry for the slow response.

Could you try setting the `name` property of the resource to `transferJobName`? It's sort of a duplicate of `transferJobsId`, they will be reconciled in the next release.

**Comment by akoenig** [comment]
Hey @mikhailshilkov, thanks for the response. Tried that. Unfortunately, the same error 🙁

**Comment by mikhailshilkov** [comment]
We pushed 0.3.0 out. I don't think it would fix your error but maybe give it a try just in case?

@viveklak Do you want to try to understand what goes wrong here?

**Comment by viveklak** [comment]
Yup I will take a look!

**Comment by viveklak** [comment]
@akoenig would you be able to take the 0.3.0 release for a spin and let us know if this is still an issue? if so I can try and repro this.

**Comment by akoenig** [comment]
@viveklak Just tested the new `0.3.0` release, but the error persists 🙁

**Comment by viveklak** [comment]
Just an update - I was able to repro the issue and working on a fix. Will update once I have confirmed a fix.

**Comment by akoenig** [comment]
Thanks a lot @viveklak. I'm looking forward to testdrive the new release as soon as it is available 🙂

**Comment by viveklak** [comment]
The fix for this should be available in the next release of Google native provider.

**Comment by akoenig** [comment]
@viveklak That is awesome 🚀 Thanks a lot for your hard work in fixing this issue :)

Do you have an ETA for the next release? Can't wait to get rid of the problem in our codebase 😄

**Comment by mikhailshilkov** [comment]
@akoenig 0.4.0 is out now

**Comment by akoenig** [comment]
@mikhailshilkov Thanks 🙂 I just tested the new release, but we're still facing the error above 🙁

This is our current definition:

```ts
   const transferJob = new gcpNative.storagetransfer.v1.TransferJob(
      transferJobName,
      {
        name: `transferJobs/${transferJobName}`,
        description: `${name}-s3-to-gcs-sync`,
        status: "ENABLED",
        schedule: {
          repeatInterval: "3600s", // every hour
          scheduleStartDate: {
            day: 1,
            month: 5,
            year: 2021,
          },
        },
        project,
        transferSpec: {
          awsS3DataSource: {
            awsAccessKey: {
              accessKeyId: config.getSecret("aws-access-key-id"),
              secretAccessKey: config.getSecret("aws-secret-access-key"),
            },
            bucketName: "my-bucket",
          },
          gcsDataSink: {
            bucketName: transferJobBucketName,
          },
          objectConditions: {
            includePrefixes: ["my/path/i-want-to-sync/"],
          },
          transferOptions: {
            deleteObjectsFromSourceAfterTransfer: false,
          },
        },
      },
      {
        dependsOn: [
          // ...
        ],
      }
    );
 ```

Performing a `pulumi up --suppress-outputs --yes --refresh` leads to `error: Preview failed: error sending request: googleapi: Error 400: Project id was not specified.`.

**Comment by mikhailshilkov** [comment]
@akoenig did you create this resource with the previous version or was it a new one that you tried to create with 0.4.0?

**Comment by viveklak** [comment]
@akoenig as @mikhailshilkov mentioned, you will have to destroy and recreate the resource with 0.4.0 for this to work unfortunately.

**Comment by akoenig** [comment]
@viveklak, @mikhailshilkov: I can confirm that after recreating the transfer job everything works as expected. Thanks a lot for the quick solution 🚀
